### ISSUE TITLE
Exception when running QC functions against FASTA `KeyError: 'is_kmer_freq_okay'`

### ISSUE THREAD

**Issue by peterk87** [phac-nml/bio_hansel#21]
I get the following error when I try to run `hansel` with a regular *Salmonella* genome FASTA file as input:

```
$ hansel SRR1958005.fasta
Traceback (most recent call last):
  File "/derp/lib/python3.6/site-packages/pandas/core/indexes/ba
se.py", line 2522, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTabl
e.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTabl
e.get_item
KeyError: 'is_kmer_freq_okay'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/derp/bin/hansel", line 11, in <module>
    sys.exit(main())
  File "/derp/lib/python3.6/site-packages/bio_hansel/main.py", l
ine 204, in main
    for input_fasta, genome_name in input_genomes]
  File "/derp/lib/python3.6/site-packages/bio_hansel/main.py", l
ine 204, in <listcomp>
    for input_fasta, genome_name in input_genomes]
  File "/derp/lib/python3.6/site-packages/bio_hansel/subtyper.py
", line 104, in subtype_fasta
    perform_quality_check(st, df, subtyping_params)
  File "/derp/lib/python3.6/site-packages/bio_hansel/quality_che
ck/__init__.py", line 49, in perform_quality_check
    status, message = func(st, df, subtyping_params)
  File "/derp/lib/python3.6/site-packages/bio_hansel/quality_che
ck/quality_check_functions.py", line 61, in check_missing_tiles
    tiles_with_hits = df[df['is_kmer_freq_okay']] # type: DataFrame
  File "/derp/lib/python3.6/site-packages/pandas/core/frame.py",
 line 2139, in __getitem__
    return self._getitem_column(key)
  File "/derp/lib/python3.6/site-packages/pandas/core/frame.py",
 line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/derp/lib/python3.6/site-packages/pandas/core/generic.py
", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/derp/lib/python3.6/site-packages/pandas/core/internals.
py", line 3838, in get
    loc = self.items.get_loc(item)
  File "/derp/lib/python3.6/site-packages/pandas/core/indexes/ba
se.py", line 2524, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTabl
e.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTabl
e.get_item
KeyError: 'is_kmer_freq_okay'
```

**Comment by hellothisisMatt** [comment]
Fix in pr #22
